blank_issues_enabled: true
contact_links:
  - name: Ask a question
    about: |
      Feel free to ask any questions or share discussions about Zugzwang.
    url: https://github.com/allansomensi/zugzwang/discussions/new
